spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/collaboration_db
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    com.climate.collaboration: DEBUG
    org.springframework.web: DEBUG
    org.springframework.messaging: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
