// MBTI Theme Configurations for all 16 types
export const mbtiThemes = {
  INTJ: {
    primary: '#4A148C',
    secondary: '#7B1FA2',
    accent: '#9C27B0',
    background: '#F3E5F5',
    text: '#1A1A1A',
    description: 'Analytical, Strategic, Independent',
    cardStyle: 'shadow-lg border-2 border-purple-900',
    buttonStyle: 'bg-purple-900 hover:bg-purple-800',
  },
  INTP: {
    primary: '#01579B',
    secondary: '#0277BD',
    accent: '#0288D1',
    background: '#E1F5FE',
    text: '#1A1A1A',
    description: 'Logical, Innovative, Abstract',
    cardStyle: 'shadow-lg border-2 border-blue-900',
    buttonStyle: 'bg-blue-900 hover:bg-blue-800',
  },
  ENTJ: {
    primary: '#B71C1C',
    secondary: '#C62828',
    accent: '#D32F2F',
    background: '#FFEBEE',
    text: '#1A1A1A',
    description: 'Decisive, Strategic, Commanding',
    cardStyle: 'shadow-lg border-2 border-red-900',
    buttonStyle: 'bg-red-900 hover:bg-red-800',
  },
  ENTP: {
    primary: '#E65100',
    secondary: '#EF6C00',
    accent: '#F57C00',
    background: '#FFF3E0',
    text: '#1A1A1A',
    description: 'Inventive, Enthusiastic, Strategic',
    cardStyle: 'shadow-lg border-2 border-orange-900',
    buttonStyle: 'bg-orange-900 hover:bg-orange-800',
  },
  INFJ: {
    primary: '#1A237E',
    secondary: '#283593',
    accent: '#3949AB',
    background: '#E8EAF6',
    text: '#1A1A1A',
    description: 'Insightful, Principled, Compassionate',
    cardStyle: 'shadow-lg border-2 border-indigo-900',
    buttonStyle: 'bg-indigo-900 hover:bg-indigo-800',
  },
  INFP: {
    primary: '#4A148C',
    secondary: '#6A1B9A',
    accent: '#7B1FA2',
    background: '#F3E5F5',
    text: '#1A1A1A',
    description: 'Idealistic, Creative, Empathetic',
    cardStyle: 'shadow-lg border-2 border-purple-800',
    buttonStyle: 'bg-purple-800 hover:bg-purple-700',
  },
  ENFJ: {
    primary: '#004D40',
    secondary: '#00695C',
    accent: '#00796B',
    background: '#E0F2F1',
    text: '#1A1A1A',
    description: 'Charismatic, Altruistic, Inspiring',
    cardStyle: 'shadow-lg border-2 border-teal-900',
    buttonStyle: 'bg-teal-900 hover:bg-teal-800',
  },
  ENFP: {
    primary: '#F57F17',
    secondary: '#F9A825',
    accent: '#FBC02D',
    background: '#FFFDE7',
    text: '#1A1A1A',
    description: 'Enthusiastic, Creative, Sociable',
    cardStyle: 'shadow-lg border-2 border-yellow-700',
    buttonStyle: 'bg-yellow-700 hover:bg-yellow-600',
  },
  ISTJ: {
    primary: '#263238',
    secondary: '#37474F',
    accent: '#455A64',
    background: '#ECEFF1',
    text: '#1A1A1A',
    description: 'Practical, Factual, Organized',
    cardStyle: 'shadow-lg border-2 border-gray-800',
    buttonStyle: 'bg-gray-800 hover:bg-gray-700',
  },
  ISFJ: {
    primary: '#3E2723',
    secondary: '#4E342E',
    accent: '#5D4037',
    background: '#EFEBE9',
    text: '#1A1A1A',
    description: 'Caring, Reliable, Detail-oriented',
    cardStyle: 'shadow-lg border-2 border-brown-900',
    buttonStyle: 'bg-brown-900 hover:bg-brown-800',
  },
  ESTJ: {
    primary: '#1B5E20',
    secondary: '#2E7D32',
    accent: '#388E3C',
    background: '#E8F5E9',
    text: '#1A1A1A',
    description: 'Organized, Direct, Traditional',
    cardStyle: 'shadow-lg border-2 border-green-900',
    buttonStyle: 'bg-green-900 hover:bg-green-800',
  },
  ESFJ: {
    primary: '#880E4F',
    secondary: '#AD1457',
    accent: '#C2185B',
    background: '#FCE4EC',
    text: '#1A1A1A',
    description: 'Caring, Social, Organized',
    cardStyle: 'shadow-lg border-2 border-pink-900',
    buttonStyle: 'bg-pink-900 hover:bg-pink-800',
  },
  ISTP: {
    primary: '#BF360C',
    secondary: '#D84315',
    accent: '#E64A19',
    background: '#FBE9E7',
    text: '#1A1A1A',
    description: 'Practical, Logical, Adaptable',
    cardStyle: 'shadow-lg border-2 border-red-800',
    buttonStyle: 'bg-red-800 hover:bg-red-700',
  },
  ISFP: {
    primary: '#4A148C',
    secondary: '#6A1B9A',
    accent: '#8E24AA',
    background: '#F3E5F5',
    text: '#1A1A1A',
    description: 'Artistic, Sensitive, Flexible',
    cardStyle: 'shadow-lg border-2 border-purple-700',
    buttonStyle: 'bg-purple-700 hover:bg-purple-600',
  },
  ESTP: {
    primary: '#FF6F00',
    secondary: '#FF8F00',
    accent: '#FFA000',
    background: '#FFF8E1',
    text: '#1A1A1A',
    description: 'Energetic, Pragmatic, Bold',
    cardStyle: 'shadow-lg border-2 border-orange-700',
    buttonStyle: 'bg-orange-700 hover:bg-orange-600',
  },
  ESFP: {
    primary: '#D81B60',
    secondary: '#EC407A',
    accent: '#F06292',
    background: '#FCE4EC',
    text: '#1A1A1A',
    description: 'Outgoing, Spontaneous, Friendly',
    cardStyle: 'shadow-lg border-2 border-pink-700',
    buttonStyle: 'bg-pink-700 hover:bg-pink-600',
  },
  DEFAULT: {
    primary: '#1976D2',
    secondary: '#2196F3',
    accent: '#42A5F5',
    background: '#E3F2FD',
    text: '#1A1A1A',
    description: 'Balanced, Versatile, Adaptive',
    cardStyle: 'shadow-lg border-2 border-blue-700',
    buttonStyle: 'bg-blue-700 hover:bg-blue-600',
  },
};

export const getMBTITheme = (mbtiType) => {
  const type = mbtiType?.toUpperCase();
  return mbtiThemes[type] || mbtiThemes.DEFAULT;
};

export default mbtiThemes;
