apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: climate-health
  labels:
    app: api-gateway
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: api-gateway
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: climate-health
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: api-gateway
        image: climate-health/api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: CLIMATE_INTEGRATOR_URL
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: CLIMATE_INTEGRATOR_URL
        - name: CLIMATE_VISUALIZER_URL
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: CLIMATE_VISUALIZER_URL
        - name: USER_SESSION_URL
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: USER_SESSION_URL
        - name: LLM_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: LLM_SERVICE_URL
        - name: COLLABORATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: COLLABORATION_SERVICE_URL
        - name: AI_MODEL_URL
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: AI_MODEL_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: climate-health-secrets
              key: JWT_SECRET
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: climate-health-secrets
              key: REDIS_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - api-gateway
              topologyKey: kubernetes.io/hostname
