apiVersion: v1
kind: Service
metadata:
  name: climate-integrator
  namespace: climate-health
  labels:
    app: climate-integrator
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  selector:
    app: climate-integrator
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: climate-integrator
  namespace: climate-health
spec:
  replicas: 2
  selector:
    matchLabels:
      app: climate-integrator
  template:
    metadata:
      labels:
        app: climate-integrator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: climate-integrator
        image: climate-health/climate-integrator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: SERVER_PORT
          value: "8081"
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: climate-health-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: climate-health-secrets
              key: POSTGRES_PASSWORD
        - name: NOAA_API_URL
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: NOAA_API_URL
        - name: NOAA_API_KEY
          valueFrom:
            secretKeyRef:
              name: climate-health-secrets
              key: NOAA_API_KEY
        - name: NASA_API_URL
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: NASA_API_URL
        - name: NASA_API_KEY
          valueFrom:
            secretKeyRef:
              name: climate-health-secrets
              key: NASA_API_KEY
        - name: WHO_API_URL
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: WHO_API_URL
        - name: OPENWEATHER_API_URL
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: OPENWEATHER_API_URL
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: climate-health-secrets
              key: OPENWEATHER_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 30
