apiVersion: v1
kind: Service
metadata:
  name: climate-visualizer
  namespace: climate-health
  labels:
    app: climate-visualizer
spec:
  ports:
  - port: 8082
    targetPort: 8082
    name: http
  selector:
    app: climate-visualizer
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: climate-visualizer
  namespace: climate-health
spec:
  replicas: 2
  selector:
    matchLabels:
      app: climate-visualizer
  template:
    metadata:
      labels:
        app: climate-visualizer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: climate-visualizer
        image: climate-health/climate-visualizer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
          name: http
        env:
        - name: SERVER_PORT
          value: "8082"
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: climate-health-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: climate-health-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: climate-health-secrets
              key: REDIS_PASSWORD
        - name: CLIMATE_INTEGRATOR_URL
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: CLIMATE_INTEGRATOR_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 30
