apiVersion: v1
kind: Service
metadata:
  name: collaboration-service
  namespace: climate-health
  labels:
    app: collaboration-service
spec:
  ports:
  - port: 8085
    targetPort: 8085
    name: http
  selector:
    app: collaboration-service
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collaboration-service
  namespace: climate-health
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collaboration-service
  template:
    metadata:
      labels:
        app: collaboration-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: collaboration-service
        image: climate-health/collaboration-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
        env:
        - name: PORT
          value: "8085"
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: LOG_LEVEL
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: climate-health-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: climate-health-secrets
              key: POSTGRES_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: climate-health-secrets
              key: REDIS_PASSWORD
        - name: WS_HEARTBEAT_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: WS_HEARTBEAT_INTERVAL
        - name: WS_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: climate-health-config
              key: WS_TIMEOUT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: climate-health-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8085
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 30
