server:
  port: 8084
  servlet:
    context-path: /

spring:
  application:
    name: llm-service

  datasource:
    url: jdbc:postgresql://localhost:5432/climate_llm
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 3000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour
      cache-null-values: false

# LLM Configuration
llm:
  provider: huggingface # Options: huggingface, openai, xai

  # Hugging Face Configuration
  huggingface:
    api-key: ${HUGGINGFACE_API_KEY:your-api-key-here}
    model: mistralai/Mistral-7B-Instruct-v0.2
    # Alternative models:
    # - meta-llama/Llama-2-7b-chat-hf
    # - google/flan-t5-large
    # - tiiuae/falcon-7b-instruct

  # OpenAI-compatible Configuration
  openai:
    api-key: ${OPENAI_API_KEY:your-api-key-here}
    model: gpt-3.5-turbo
    base-url: https://api.openai.com/v1
    # Alternative models:
    # - gpt-4
    # - gpt-4-turbo-preview

  # xAI Configuration
  xai:
    api-key: ${XAI_API_KEY:your-api-key-here}
    model: grok-beta
    # Alternative models:
    # - grok-1

  # Rate Limiting
  rate-limit:
    requests-per-minute: 60
    requests-per-hour: 1000

  # Response Configuration
  response:
    max-tokens: 500
    temperature: 0.7
    top-p: 0.9
    timeout-seconds: 60

# Logging
logging:
  level:
    root: INFO
    com.climate.llm: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/llm-service.log
    max-size: 10MB
    max-history: 30

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# MBTI Configuration
mbti:
  cache:
    enabled: true
    ttl-minutes: 60
  personality-types:
    - INTJ
    - INTP
    - ENTJ
    - ENTP
    - INFJ
    - INFP
    - ENFJ
    - ENFP
    - ISTJ
    - ISFJ
    - ESTJ
    - ESFJ
    - ISTP
    - ISFP
    - ESTP
    - ESFP
